version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: 
          name: Dependencies
          command: go get -v -t -d ./...

      - run:
          name: Tests with Coverage
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            go test -coverprofile cp.out ./...
            ./cc-test-reporter after-build -t gocov -p github.com/calvinchengx/gin-go-pg -r ${TEST_REPORTER_ID}
